server.document-root = "/data/data/com.termux/files/home/alzikrayat/public"
server.port = 8080

server.modules += ( "mod_cgi", "mod_rewrite" )

cgi.assign = ( ".php" => "" )

url.rewrite-once = (
  "^/(.*)\.(.*)$" => "$0",
  "^/(.*)$" => "/index.php"
)
